# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michelle Wen
tagline:          'A Personal Website'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://michellewen3.github.io/
baseurl:          '/michellewen3.github.io/'

author:
  name:           'Michelle Wen'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/michellewen3/michellewen3.github.io
